import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Camera, Check, ChevronDown, CircleHelp, Globe2, Heart, ImagePlus, KeyRound, Menu, MessageCircle, Search, ThumbsUp, X } from 'lucide-react';
import './styles.css';
import './home.css';
import './motion.css';
import './access.css';
import { mediaUrl, supabase, supabaseConfigured } from './supabaseClient';

const initialCouples = [];
const heroFallbackUrl = 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1800&q=90';
const homeHeroUrl = 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=2200&q=92';
const homeSlides = [
  homeHeroUrl.replace('w=2200&q=92','w=1200&q=80'),
  'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80'
];
const heroStyles = [
  { id:'golden', label:'Golden celebration', url:heroFallbackUrl, crop:{scale:1,x:0,y:0} },
  { id:'romance', label:'Modern romance', url:'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} },
  { id:'garden', label:'Garden ceremony', url:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} },
  { id:'portrait', label:'Classic portrait', url:'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} },
  { id:'floral', label:'Floral celebration', url:'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} },
  { id:'timeless', label:'Timeless love', url:'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} },
  { id:'sunset', label:'Sunset vows', url:'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} },
  { id:'together', label:'Together forever', url:'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=1800&q=90', crop:{scale:1,x:0,y:0} }
];
function imageFallback(event) { event.currentTarget.onerror = null; event.currentTarget.src = heroFallbackUrl; }
function mapWall(row) { return { ...row, id:row.id, username:row.slug, name:row.couple_names, date:row.wedding_date, venue:row.venue, image:row.hero_path ? {url:mediaUrl(row.hero_path),crop:row.hero_crop||{scale:1,x:0,y:0}} : defaultHero, quote:row.welcome_message }; }
function mapWish(row) { const reactions=(row.wish_reactions||[]).reduce((all,item)=>({...all,[item.reaction]:(all[item.reaction]||0)+1}),{like:0,love:0}); return {...row, coupleId:row.wall_id, name:row.guest_name, message:row.message, date:new Date(row.created_at).toLocaleString(), images:(row.wish_media||[]).sort((a,b)=>a.position-b.position).map(item=>mediaUrl(item.storage_path)).filter(Boolean), reactions, comments:(row.comments||[]).filter(item=>item.status==='published').map(item=>({id:item.id,text:item.body,date:new Date(item.created_at).toLocaleString()}))}; }
async function ensureOnlineUser() { if (!supabase) throw new Error('Supabase settings are missing.'); const {data:{session},error:sessionError}=await supabase.auth.getSession(); if(sessionError) throw sessionError; if(session?.user) return session.user; const {data,error}=await supabase.auth.signInAnonymously(); if(error) throw error; return data.user; }
function isAnonymousUser(user) { return user?.is_anonymous === true || user?.app_metadata?.provider === 'anonymous' || (!user?.email && !user?.phone); }
async function uploadFile(file, folder) { const user=await ensureOnlineUser(); const extension=(file.name?.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg'; const path=`${user.id}/${folder}/${crypto.randomUUID()}.${extension}`; const {error}=await supabase.storage.from('celebration-media').upload(path,file,{contentType:file.type,upsert:false}); if(error) throw error; return path; }
const defaultHero = heroStyles[0];
const countries = [{ country:'Afghanistan',flag:'🇦🇫',code:'en'},{ country:'Albania',flag:'🇦🇱',code:'en'},{ country:'Algeria',flag:'🇩🇿',code:'ar'},{ country:'Australia',flag:'🇦🇺',code:'en'},{ country:'Austria',flag:'🇦🇹',code:'en'},{ country:'Bangladesh',flag:'🇧🇩',code:'en'},{ country:'Belgium',flag:'🇧🇪',code:'en'},{ country:'Brazil',flag:'🇧🇷',code:'en'},{ country:'Canada',flag:'🇨🇦',code:'en'},{ country:'China',flag:'🇨🇳',code:'en'},{ country:'Colombia',flag:'🇨🇴',code:'en'},{ country:'Denmark',flag:'🇩🇰',code:'en'},{ country:'Egypt',flag:'🇪🇬',code:'ar'},{ country:'Ethiopia',flag:'🇪🇹',code:'en'},{ country:'Finland',flag:'🇫🇮',code:'en'},{ country:'France',flag:'🇫🇷',code:'en'},{ country:'Germany',flag:'🇩🇪',code:'en'},{ country:'Ghana',flag:'🇬🇭',code:'en'},{ country:'India',flag:'🇮🇳',code:'en'},{ country:'Indonesia',flag:'🇮🇩',code:'en'},{ country:'Ireland',flag:'🇮🇪',code:'en'},{ country:'Italy',flag:'🇮🇹',code:'it'},{ country:'Japan',flag:'🇯🇵',code:'en'},{ country:'Jordan',flag:'🇯🇴',code:'ar'},{ country:'Kenya',flag:'🇰🇪',code:'en'},{ country:'Malaysia',flag:'🇲🇾',code:'en'},{ country:'Mexico',flag:'🇲🇽',code:'en'},{ country:'Morocco',flag:'🇲🇦',code:'ar'},{ country:'Netherlands',flag:'🇳🇱',code:'en'},{ country:'New Zealand',flag:'🇳🇿',code:'en'},{ country:'Nigeria',flag:'🇳🇬',code:'en'},{ country:'Norway',flag:'🇳🇴',code:'en'},{ country:'Pakistan',flag:'🇵🇰',code:'en'},{ country:'Philippines',flag:'🇵🇭',code:'en'},{ country:'Poland',flag:'🇵🇱',code:'en'},{ country:'Portugal',flag:'🇵🇹',code:'en'},{ country:'Qatar',flag:'🇶🇦',code:'ar'},{ country:'Saudi Arabia',flag:'🇸🇦',code:'ar'},{ country:'Somalia',flag:'🇸🇴',code:'so'},{ country:'South Africa',flag:'🇿🇦',code:'en'},{ country:'South Korea',flag:'🇰🇷',code:'en'},{ country:'Spain',flag:'🇪🇸',code:'en'},{ country:'Sweden',flag:'🇸🇪',code:'sv'},{ country:'Switzerland',flag:'🇨🇭',code:'en'},{ country:'Tanzania',flag:'🇹🇿',code:'en'},{ country:'Thailand',flag:'🇹🇭',code:'en'},{ country:'Turkey',flag:'🇹🇷',code:'en'},{ country:'Uganda',flag:'🇺🇬',code:'en'},{ country:'United Arab Emirates',flag:'🇦🇪',code:'ar'},{ country:'United Kingdom',flag:'🇬🇧',code:'en'},{ country:'United States',flag:'🇺🇸',code:'en'},{ country:'Yemen',flag:'🇾🇪',code:'ar'}];
const countryDialCodes = {Afghanistan:'+93',Albania:'+355',Algeria:'+213',Australia:'+61',Austria:'+43',Bangladesh:'+880',Belgium:'+32',Brazil:'+55',Canada:'+1',China:'+86',Colombia:'+57',Denmark:'+45',Egypt:'+20',Ethiopia:'+251',Finland:'+358',France:'+33',Germany:'+49',Ghana:'+233',India:'+91',Indonesia:'+62',Ireland:'+353',Italy:'+39',Japan:'+81',Jordan:'+962',Kenya:'+254',Malaysia:'+60',Mexico:'+52',Morocco:'+212',Netherlands:'+31','New Zealand':'+64',Nigeria:'+234',Norway:'+47',Pakistan:'+92',Philippines:'+63',Poland:'+48',Portugal:'+351',Qatar:'+974','Saudi Arabia':'+966',Somalia:'+252','South Africa':'+27','South Korea':'+82',Spain:'+34',Sweden:'+46',Switzerland:'+41',Tanzania:'+255',Thailand:'+66',Turkey:'+90',Uganda:'+256','United Arab Emirates':'+971','United Kingdom':'+44','United States':'+1',Yemen:'+967'};
const dictionary = {
  en: { welcome: 'Bring Your Loved Ones Closer', tagline: 'Create a beautiful live wedding wall for greetings, photos, and wishes from all around the world.', search: 'Search by couple name (e.g. emma-jack)...', searchBtn: 'Search Wall', ready: 'Ready Couples', leave: 'Leave a Blessing', name: 'Guest Name', country: 'Country of Residence', emoji: 'Select Celebratory Emoji', message: 'Your Message Wishes', send: 'Send Blessing', wishes: 'Wishes from Loved Ones' },
  so: { welcome: 'Ku dhoweyso ehelkaaga iyo saaxiibadaada', tagline: 'Arooskaaga u yeel Gidgi Casri ah si martidu kuugu soo dirto hambalyada aduunka oo dhan.', search: 'Ku raadi magaca lamaanaha (Tusaale: emma-jack)...', searchBtn: 'Raadi Gidgiga', ready: 'Lamaanayaasha Diyaar ah', leave: 'Ku Deeq Duco', name: 'Magaca Martida', country: 'Dalka laga soo diray', emoji: 'Dooro Emoji Farxadeed', message: 'Fariintaada iyo Ducada', send: 'Dir Duco & Hambalyo', wishes: 'Ducooyinka ay Martidu soo dirtay' },
  it: { welcome: 'Avvicina i Tuoi Cari', tagline: 'Crea una splendida bacheca di nozze interattiva per auguri, foto e video da tutto il mondo.', search: 'Cerca per nome della coppia...', searchBtn: 'Cerca Bacheca', ready: 'Coppie Registrate', leave: 'Lascia un Augurio', name: "Nome dell'Ospite", country: 'Paese di Residenza', emoji: 'Seleziona Emoji Festiva', message: 'I tuoi Auguri di Cuore', send: 'Invia Augurio', wishes: 'Auguri dai Tuoi Cari' },
  sv: { welcome: 'För dina nära och kära närmare', tagline: 'Skapa en vacker levande vägg för lyckönskningar, foton och videor från hela världen.', search: 'Sök på brudparets namn...', searchBtn: 'Sök efter Vägg', ready: 'Registrerade Par', leave: 'Lämna en Hälsning', name: 'Gästens Namn', country: 'Bosättningsland', emoji: 'Välj Festlig Emoji', message: 'Dina Lyckönskningar', send: 'Skicka Hälsning', wishes: 'Hälsningar från Nära och Kära' },
  ar: { welcome: 'قرّب أحبّاءك إليك في يومك الكبير', tagline: 'أنشئ جدار تهنئة تفاعلي لاستقبال التبريكات والصور والرسائل من جميع أنحاء العالم.', search: 'ابحث باسم الزوجين...', searchBtn: 'ابحث عن الجدار', ready: 'الأزواج المتاحون', leave: 'أرسل تهنئة ودعاء', name: 'اسم الضيف', country: 'بلد الإقامة', emoji: 'اختر الإيموجي المناسب', message: 'رسالة التهنئة الخاصة بك', send: 'إرسال التهنئة', wishes: 'تبريكات الأحبة والأصدقاء' }
};
const starterWishes = [];

function App() {
  const [page, setPage] = useState('landing'); const [theme, setTheme] = useState('cream'); const [lang, setLang] = useState('en'); const [couples, setCouples] = useState([]); const [selected, setSelected] = useState(null);
  const [langOpen, setLangOpen] = useState(false); const [guideOpen, setGuideOpen] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const [query, setQuery] = useState(''); const [alert, setAlert] = useState('');
  const [wishes, setWishes] = useState(() => JSON.parse(localStorage.getItem('congrats-wishes') || '[]')); const [guest, setGuest] = useState(''); const [country, setCountry] = useState('United Kingdom'); const [emoji, setEmoji] = useState('✨'); const [wish, setWish] = useState(''); const [file, setFile] = useState(null); const [activeWish, setActiveWish] = useState(null); const [adminSession, setAdminSession] = useState(false); const fileInput = useRef(null);
  useEffect(() => { if ('scrollRestoration' in window.history) window.history.scrollRestoration = 'manual'; window.scrollTo({top:0,left:0,behavior:'auto'}); }, []);
  const t = dictionary[lang]; const rtl = lang === 'ar';
  async function loadWalls() { const {data,error}=await supabase.from('walls').select('*').eq('status','active').order('created_at',{ascending:false}); if(error) throw error; setCouples((data||[]).map(mapWall)); }
  async function loadWishes(wallId) { const {data,error}=await supabase.from('wishes').select('*, wish_media(*), wish_reactions(*), comments(*)').eq('wall_id',wallId).eq('status','published').order('created_at',{ascending:false}); if(error) throw error; const formatted=(data||[]).map(mapWish); setWishes(formatted); return formatted; }
  async function openMyDashboard() { try { const user=await ensureOnlineUser(); if(isAnonymousUser(user)) { setAlert('Use your registered email or mobile number to access your dashboard.'); return; } await supabase.rpc('claim_walls_for_current_identity'); const {data,error}=await supabase.from('walls').select('*').eq('owner_id',user.id).neq('status','removed').order('created_at',{ascending:false}).limit(1).maybeSingle(); if(error) throw error; if(!data) { setAlert('No wedding wall was found for this verified email or mobile number.'); return; } const wall=mapWall(data); setSelected(wall); await loadWishes(wall.id); navigate('dashboard'); } catch(error) { setAlert(`Could not open your dashboard: ${error.message}`); } }
  useEffect(() => { let live=true; (async()=>{ try { if(!supabaseConfigured) throw new Error('Supabase environment values are missing.'); const user=await ensureOnlineUser(); const {error:visitError}=await supabase.from('site_visits').insert({visitor_id:user.id,page_path:window.location.pathname||'/'}); if(visitError) console.warn('Visit tracking unavailable:',visitError.message); const {data,error}=await supabase.from('walls').select('*').eq('status','active').order('created_at',{ascending:false}); if(error) throw error; if(live) setCouples((data||[]).map(mapWall)); } catch(error) { if(live) setAlert(`Online connection failed: ${error.message}`); } })(); return ()=>{live=false}; }, []);
  useEffect(() => { if(!supabase) return; const refresh=()=>loadWalls().catch(()=>{}); const interval=window.setInterval(refresh,30000); const channel=supabase.channel('public-walls-refresh').on('postgres_changes',{event:'*',schema:'public',table:'walls'},refresh).subscribe(); return ()=>{window.clearInterval(interval);supabase.removeChannel(channel)}; }, []);
  useEffect(() => { if(!supabase) return; const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{ if(event==='SIGNED_IN' && session?.user && !isAnonymousUser(session.user)) setTimeout(async()=>{ const {data:isAdmin}=await supabase.rpc('is_admin'); if(!isAdmin) openMyDashboard(); },0); }); return ()=>subscription.unsubscribe(); }, []);
  useEffect(() => { if(!supabase || !selected?.id) return; const refresh=()=>loadWishes(selected.id).catch(()=>{}); const interval=window.setInterval(refresh,20000); const channel=supabase.channel(`wall-live-${selected.id}`).on('postgres_changes',{event:'*',schema:'public',table:'wishes',filter:`wall_id=eq.${selected.id}`},refresh).on('postgres_changes',{event:'*',schema:'public',table:'wish_reactions'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'comments'},refresh).subscribe(); return ()=>{window.clearInterval(interval);supabase.removeChannel(channel)}; }, [selected?.id]);
  useEffect(() => { if(!adminSession) return; (async()=>{ try { const [{data:wallRows,error:wallError},{data:wishRows,error:wishError}]=await Promise.all([supabase.from('walls').select('*').order('created_at',{ascending:false}),supabase.from('wishes').select('*, wish_media(*), wish_reactions(*), comments(*)').order('created_at',{ascending:false})]); if(wallError) throw wallError; if(wishError) throw wishError; setCouples((wallRows||[]).map(mapWall)); setWishes((wishRows||[]).map(mapWish)); } catch(error) { setAlert(`Could not load admin data: ${error.message}`); } })(); }, [adminSession]);
  function navigate(next) { setPage(next); setMenuOpen(false); window.scrollTo({top:0, behavior:'smooth'}); }
  function browseSection(id) { setPage('landing'); setMenuOpen(false); setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior:'smooth', block:'start' }), 100); }
  function openFindWall() { if (page !== 'landing') setPage('landing'); setMenuOpen(false); window.scrollTo({top:0, behavior:'smooth'}); setTimeout(() => document.querySelector('.search-box input')?.focus(), 350); }
  async function findWall(e) { e.preventDefault(); const slug=query.trim().toLowerCase().replace(/^@/, ''); if(!slug) return; try { const {data,error}=await supabase.from('walls').select('*').eq('slug',slug).eq('status','active').maybeSingle(); if(error) throw error; if(!data) { setAlert('Wall not found. Please check the exact wall address and try again.'); return; } const found=mapWall(data); setSelected(found); await loadWishes(found.id); navigate('wall'); } catch(error) { setAlert(`Could not open this wall: ${error.message}`); } }
  async function addWish(e) { e.preventDefault(); if (!guest.trim() || !wish.trim() || !selected) { setAlert('Please add your name and a message before sending.'); return; } try { const user=await ensureOnlineUser(); const {data:created,error}=await supabase.from('wishes').insert({wall_id:selected.id,guest_name:guest.trim(),country,country_code:countries.find(c=>c.country===country)?.code,emoji,message:wish.trim()}).select().single(); if(error) throw error; for(const [position,entry] of (file?.images||[]).entries()) { if(!entry.file) continue; const storage_path=await uploadFile(entry.file,`wishes/${created.id}`); const {error:mediaError}=await supabase.from('wish_media').insert({wish_id:created.id,uploaded_by:user.id,storage_path,media_type:'image',position}); if(mediaError) throw mediaError; } await loadWishes(selected.id); setGuest(''); setWish(''); setFile(null); setAlert('Your blessing is now live on the celebration wall.'); } catch(error) { setAlert(`Your blessing could not be sent: ${error.message}`); } }
  function chooseFile(e) { const files=Array.from(e.target.files||[]); if(!files.length)return; setFile({name:files.length===1?files[0].name:`${files.length} files selected`,video:files.some(f=>f.type.startsWith('video/')),urls:files.filter(f=>f.type.startsWith('image/')).map(f=>URL.createObjectURL(f))}); }
  async function reactToWish(id,type) { try { await ensureOnlineUser(); const {error}=await supabase.from('wish_reactions').upsert({wish_id:id,reaction:type},{onConflict:'wish_id,user_id,reaction',ignoreDuplicates:true}); if(error) throw error; if(selected) await loadWishes(selected.id); } catch(error) { setAlert(`Reaction could not be saved: ${error.message}`); } }
  async function commentOnWish(id,text) { if(!text.trim())return; try { await ensureOnlineUser(); const {error}=await supabase.from('comments').insert({wish_id:id,guest_name:'Guest',body:text.trim()}); if(error) throw error; if(selected) await loadWishes(selected.id); } catch(error) { setAlert(`Comment could not be sent: ${error.message}`); } }
  function createWall(details) { const wall = { id:String(Date.now()), username:details.username, name:details.names, date:details.eventDate, venue:details.venue, image:details.hero?.images?.[0]||defaultHero, quote:'“Welcome to our celebration wall. Thank you for sharing in our joy!”', ...details }; if (couples.some(c=>c.username===wall.username)) { setAlert(`@${wall.username} is already taken. Please choose another address.`); return; } setCouples(prev=>[...prev,wall]); setSelected(wall); setAlert(`Hambalyo ${wall.name}! Your wall is ready and searchable at @${wall.username}.`); navigate('dashboard'); }
  async function createWallOnline(details) { try { const user=await ensureOnlineUser(); const hero=details.hero?.images?.[0]; let hero_path=hero?.url||null; if(hero?.file) hero_path=await uploadFile(hero.file,'walls/hero'); const {data,error}=await supabase.from('walls').insert({owner_id:user.id,slug:details.username,couple_names:details.names,wedding_date:details.eventDate,venue:details.venue||null,country:details.home,contact_email:details.email,contact_phone:details.phone,hero_path,hero_crop:hero?.crop||{scale:1,x:0,y:0}}).select().single(); if(error) throw error; const wall=mapWall(data); setCouples(prev=>[wall,...prev]); setSelected(wall); setAlert(`Hambalyo ${wall.name}! Your wall is ready and searchable at @${wall.username}.`); navigate('wall'); } catch(error) { const message=error.code==='23505' ? `@${details.username} is already taken. Please choose another address.` : `Your wall could not be created: ${error.message}`; setAlert(message); } }
  return <div className={`app ${theme}`} dir={rtl?'rtl':'ltr'}>
    <nav className="source-nav"><div className="nav-inner"><button className="source-logo" onClick={()=>navigate('landing')}>CONGRATS</button><div className={menuOpen?'links open':'links'}><button onClick={()=>browseSection('home')}>Home</button><button onClick={()=>browseSection('find')}>Find a Wall</button><button className="register-link" onClick={()=>browseSection('register')}>Register your wall</button><button className="gold-link" onClick={()=>browseSection('guide')}><CircleHelp size={15}/> User Guide & Registry Info</button></div><div className="controls"><button className="admin-access" onClick={()=>navigate(adminSession?'admin':'adminLogin')}><KeyRound size={14}/> Admin</button><div className="locale"><button className="language-button" onClick={()=>setLangOpen(!langOpen)}><Globe2 size={15}/><span>{lang}</span></button>{langOpen&&<LanguagePanel onPick={(code)=>{setLang(code);setLangOpen(false)}}/>}</div><div className="themes"><button className={theme==='cream'?'selected':''} onClick={()=>setTheme('cream')}>Cream</button><button className={theme==='daylight'?'selected day':''} onClick={()=>setTheme('daylight')}>Day</button><button className={theme==='nightlight'?'selected night':''} onClick={()=>setTheme('nightlight')}>Night</button></div><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></div></div></nav>
    {alert&&<div className="toast"><Check size={17}/><span>{alert}</span><button onClick={()=>setAlert('')}><X size={15}/></button></div>}
    <main className="content">{page==='landing'&&<div className="scroll-platform"><section id="home"><Landing register={()=>browseSection('register')} find={()=>browseSection('find')}/></section><section id="find" className="scroll-section"><FindWallPage t={t} query={query} setQuery={setQuery} findWall={findWall}/></section><section id="register" className="scroll-section"><Register done={createWallOnline}/></section><section id="guide" className="scroll-section"><GuidePage/></section></div>}{page==='wall'&&selected&&<Wall t={t} selected={selected} wishes={wishes.filter(w=>w.coupleId===selected.id)} guest={guest} setGuest={setGuest} country={country} setCountry={setCountry} emoji={emoji} setEmoji={setEmoji} wish={wish} setWish={setWish} file={file} setFile={setFile} addWish={addWish} reactToWish={reactToWish} openWish={setActiveWish}/>} {page==='dashboard'&&selected&&<Dashboard couple={selected} wishes={wishes.filter(w=>w.coupleId===selected.id)} openWall={async()=>{await loadWishes(selected.id);navigate('wall')}} />} {page==='adminLogin'&&<AdminLogin success={()=>{setAdminSession(true);navigate('admin')}}/>} {page==='admin'&&adminSession&&<Admin couples={couples} wishes={wishes} setWishes={setWishes} setCouples={setCouples} logout={()=>{setAdminSession(false);navigate('landing')}}/>}</main>
    <Footer openGuide={()=>browseSection('guide')} goHome={()=>browseSection('home')}/>{activeWish&&<WishModal wish={wishes.find(w=>w.id===activeWish.id)||activeWish} close={()=>setActiveWish(null)} reactToWish={reactToWish} commentOnWish={commentOnWish}/>}</div>;
}

function LanguagePanel({onPick}) { const [search,setSearch]=useState(''); const visible=countries.filter(c=>c.country.toLowerCase().includes(search.toLowerCase())); return <div className="language-panel"><h3><Globe2 size={17}/> Select Country / Language</h3><input autoFocus placeholder="Search country..." value={search} onChange={e=>setSearch(e.target.value)}/><div>{visible.map(c=><button key={c.country} onClick={()=>onPick(c.code)}><span>{c.flag}</span><label>{c.country}<small>{c.code.toUpperCase()}</small></label><b>{c.code.toUpperCase()}</b></button>)}</div></div> }
function Landing({register,find}) { const [activeSlide,setActiveSlide]=useState(0); useEffect(()=>{const timer=window.setInterval(()=>setActiveSlide(current=>(current+1)%homeSlides.length),5600);return()=>window.clearInterval(timer)},[]); const src=homeSlides[activeSlide]; return <section className="home-page"><div className="home-copy"><span className="portal-chip">GLOBAL CELEBRATION & WEDDING PLATFORM</span><h1>Celebrate the people and moments <em>you love.</em></h1><p>CONGRATS gives every couple one beautiful place to collect wishes, photos, and memories from around the world.</p><div className="home-actions"><button className="gold-button" onClick={register}>Create your wall <Heart size={15} fill="currentColor"/></button><button className="home-secondary" onClick={find}>Find a wall <Search size={15}/></button></div></div><div className="home-photo home-gallery"><img key={src} src={src} onError={imageFallback} className="active" alt="Wedding celebration" fetchPriority="high"/><div><span>YOUR CELEBRATION, YOUR STORY</span><b>Made to be shared.</b><p>A single place for every memory.</p><nav className="home-slide-dots" aria-label="Wedding photo gallery">{homeSlides.map((_,index)=><button key={index} className={index===activeSlide?'active':''} onClick={()=>setActiveSlide(index)} aria-label={`Show wedding photo ${index+1}`}/>)}</nav></div></div><section className="home-followup"><span className="section-label">MADE FOR THE MOMENTS THAT MATTER</span><h2>One address. Every kind word.</h2><div><p>Keep scrolling on Home to see why couples choose CONGRATS.</p><p>Guests can find a wall from any device, share a blessing, attach photos, and return whenever they wish.</p></div></section></section> }
function FindWallPage({t,query,setQuery,findWall}) { return <section className="find-page"><span className="portal-chip">FIND A CELEBRATION</span><h1>Every wall begins<br/>with a shared address.</h1><p>Enter the couple’s wall address to open their celebration, leave a message, and share your love.</p><form className="search-box" onSubmit={findWall}><span>@</span><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. ayaan-hamza"/><button>{t.searchBtn}<Search size={16}/></button></form><p className="search-help">The couple will share their address in this format: congrats.com/their-wall-name</p><div className="find-steps"><article><b>1</b><span>Receive the couple’s personal CONGRATS address.</span></article><article><b>2</b><span>Enter the address above and open the wall.</span></article><article><b>3</b><span>Leave a wish, photo, reaction, or comment.</span></article></div></section> }
function GuidePage() { return <section className="guide-page"><span className="portal-chip">HOW CONGRATS WORKS</span><h1>Simple for couples.<br/>Warm for every guest.</h1><div className="guide-page-grid"><article><b>01</b><h2>Create a wall</h2><p>Choose a unique address, add your wedding date, venue, and a hero photo that feels like you.</p></article><article><b>02</b><h2>Share your address</h2><p>Send your personal CONGRATS link to family and friends anywhere in the world.</p></article><article><b>03</b><h2>Collect the love</h2><p>Guests can leave wishes, photos, reactions, and comments on your celebration wall.</p></article></div></section> }
function BrowsePreviews() { return <section className="browse-previews"><div className="preview-intro"><span className="section-label">SEE THE EXPERIENCE FIRST</span><h2>Scroll through the platform before choosing a path.</h2><p>These previews let every visitor understand what they can do, without opening another page.</p></div><div className="preview-grid"><article className="page-preview create-preview"><div className="preview-top"><b>01</b><span>Create a wedding wall</span></div><h3>Your celebration, beautifully yours.</h3><div className="preview-fields"><span>Couple names</span><span>Wedding date</span><span>Venue / city</span></div><div className="preview-photo"><img src={heroStyles[0].url} alt="Wedding style preview"/><i>Choose, crop or replace your hero photo</i></div></article><article className="page-preview find-preview"><div className="preview-top"><b>02</b><span>Find a celebration wall</span></div><h3>Share the joy from anywhere.</h3><div className="preview-search"><span>@</span><em>Enter a wall address</em><i>Search</i></div><p>Open a couple’s shared address, then leave a message, photos, reactions, and comments.</p><div className="preview-wish"><Heart size={15} fill="currentColor"/> A private space for every celebration</div></article></div></section> }
function ScrollJourney({open}) { return <section className="scroll-journey"><div><span className="section-label">EXPLORE AT YOUR OWN PACE</span><h2>Choose a path, or keep scrolling to learn how it works.</h2><p>Both options stay available throughout the platform, so visitors can use whichever route feels easiest.</p></div><div className="journey-grid"><button onClick={()=>open('register')}><b>01</b><span><strong>Create a wall</strong><small>Set up a celebration for your couple.</small></span><i>Open →</i></button><button onClick={()=>open('find')}><b>02</b><span><strong>Find a wall</strong><small>Open a shared celebration link.</small></span><i>Search →</i></button></div></section> }
function Feature({n,title,children}) { return <article className={`feature feature-${n}`}><b>{n}</b><h3>{n}. {title}</h3><p>{children}</p></article> }
function Wall(props) { const {t,selected,wishes,guest,setGuest,country,setCountry,emoji,setEmoji,wish,setWish,file,setFile,addWish,reactToWish,openWish}=props; const [sort,setSort]=useState('newest'); const hero=typeof selected.image==='string'?{url:selected.image,crop:{scale:1,x:0,y:0}}:selected.image; const date=new Date(`${selected.date}T12:00:00`).toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'}); const orderedWishes=[...wishes].sort((a,b)=>sort==='newest'?new Date(b.created_at||b.date)-new Date(a.created_at||a.date):new Date(a.created_at||a.date)-new Date(b.created_at||b.date)); return <section className="wall"><div className="wall-hero"><img src={hero.url} style={cropStyle(hero.crop)} alt={selected.name}/><div><span>CONGRATS LIVE WEDDING PORTAL</span><h1>{selected.name}</h1><p>📅 {date}{selected.venue&&<><i/> 📍 {selected.venue}</>}<i/> 🔗 congrats.com/{selected.username}</p></div></div><div className="couple-quote"><p>{selected.quote}</p><b/></div><div className="wall-columns"><aside className="form-card"><h2>{t.leave}</h2><form onSubmit={addWish}><label>{t.name}<input value={guest} onChange={e=>setGuest(e.target.value)} placeholder="Enter your full name" required/></label><div><label>{t.country}</label><CountryPicker value={country} onChange={setCountry}/></div><div><label>{t.emoji}</label><div className="emojis">{['✨','💍','🥂','❤️','🌹','⭐'].map(x=><button type="button" key={x} onClick={()=>setEmoji(x)} className={emoji===x?'active':''}>{x}</button>)}</div></div><label>{t.message}<textarea value={wish} onChange={e=>setWish(e.target.value)} placeholder="Write a heartfelt wish..." required/></label><MediaUploadField value={file} onChange={setFile}/><button className="gold-button">{t.send}<Heart size={15} fill="currentColor"/></button></form></aside><section className="feed"><div className="feed-title"><div><span>LIVE CELEBRATION FEED</span><h2>{t.wishes} <b>{wishes.length}</b></h2></div><label className="wish-sort">Sort wishes<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div><div className="wish-grid">{orderedWishes.map(w=><Wish key={w.id} w={w} reactToWish={reactToWish} openWish={openWish}/>)}</div></section></div></section> }
function cropStyle(crop={}) { return { transform:`scale(${crop.scale||1}) translate(${crop.x||0}%, ${crop.y||0}%)`, transformOrigin:'center', objectFit:'cover' }; }
function MediaCropField({value,onChange,hero=false}) { const [editing,setEditing]=useState(null); const [showAll,setShowAll]=useState(false); const input=useRef(null); const images=value?.images||[]; function filesSelected(event){const entries=Array.from(event.target.files||[]).filter(file=>file.type.startsWith('image/')).map(file=>({url:URL.createObjectURL(file),file,crop:{scale:1,x:0,y:0}}));if(entries.length){onChange({images:entries});setEditing(0)}event.target.value=''} function updateCrop(crop){onChange({images:images.map((image,index)=>index===editing?{...image,crop}:image)});setEditing(null)} function chooseStyle(style){onChange({images:[{url:style.url,crop:{scale:1,x:0,y:0}}]});setEditing(0)} const shown=showAll?heroStyles:heroStyles.slice(0,4); return <div className={`crop-field ${hero?'hero-crop-field':''}`}><input ref={input} className="hidden-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple={!hero} onChange={filesSelected}/>{hero&&<div className="hero-style-picker"><div className="style-heading"><span>CHOOSE A STARTING STYLE</span><button type="button" onClick={()=>setShowAll(!showAll)}>{showAll?'Show less':'View more styles'}</button></div><div className="style-grid">{shown.map(style=><button type="button" key={style.id} onClick={()=>chooseStyle(style)}><img src={style.url} onError={imageFallback} alt={style.label}/><span>{style.label}</span></button>)}</div></div>}<button className="media" type="button" onClick={()=>input.current?.click()}><ImagePlus size={17}/>{images.length?'Replace with your photo':'Upload your photo'}<Camera size={16}/></button>{images.length>0&&<div className="crop-thumbs">{images.map((image,index)=><button type="button" key={`${image.url}-${index}`} onClick={()=>setEditing(index)}><img src={image.url} style={cropStyle(image.crop)} alt="Selected upload"/><span>Edit crop</span></button>)}</div>}{editing!==null&&<CropEditor image={images[editing]} hero={hero} onCancel={()=>setEditing(null)} onSave={updateCrop}/>}</div> }
function MediaUploadField({value,onChange}) { const input=useRef(null); const images=value?.images||[]; function filesSelected(event){const entries=Array.from(event.target.files||[]).filter(file=>file.type.startsWith('image/')).map(file=>({url:URL.createObjectURL(file),file}));if(entries.length)onChange({images:[...images,...entries]});event.target.value=''} function removeImage(index){onChange({images:images.filter((_,itemIndex)=>itemIndex!==index)})} return <div className="upload-field"><input ref={input} className="hidden-file" type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={filesSelected}/><button className="media" type="button" onClick={()=>input.current?.click()}><ImagePlus size={17}/>{images.length?'Add more photos':'Attach photos'}<Camera size={16}/></button>{images.length>0&&<div className="upload-previews">{images.map((image,index)=>{const url=typeof image==='string'?image:image.url;return <span className="upload-preview" key={`${url}-${index}`}><img src={url} alt={`Selected upload ${index+1}`}/><button type="button" onClick={()=>removeImage(index)} aria-label="Remove photo"><X size={12}/></button></span>})}</div>}<small className="upload-note">You can select several photos, remove any photo, then send them with your blessing.</small></div> }
function CropEditor({image,hero,onCancel,onSave}) { const [scale,setScale]=useState(image.crop?.scale||1); const [x,setX]=useState(image.crop?.x||0); const [y,setY]=useState(image.crop?.y||0); const drag=useRef(null); function startDrag(event){const rect=event.currentTarget.getBoundingClientRect();drag.current={pointer:event.pointerId,startX:event.clientX,startY:event.clientY,x,y,width:rect.width,height:rect.height};event.currentTarget.setPointerCapture?.(event.pointerId)} function moveDrag(event){if(!drag.current)return;const move=drag.current;setX(Math.max(-35,Math.min(35,move.x+((event.clientX-move.startX)/move.width)*100)));setY(Math.max(-35,Math.min(35,move.y+((event.clientY-move.startY)/move.height)*100)))} function endDrag(){drag.current=null} return <div className="overlay crop-overlay"><section className="crop-editor"><button className="close" onClick={onCancel}><X/></button><span>ADJUST YOUR PHOTO</span><h2>{hero?'Choose the perfect hero framing':'Crop your shared photo'}</h2><p className="crop-tip">On phone, drag the photo with your finger. On desktop, drag it or use the controls below.</p><div className={`crop-preview ${hero?'wide':''}`} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag}><img src={image.url} style={cropStyle({scale,x,y})} alt="Crop preview"/></div><label>ZOOM <input type="range" min="1" max="2.5" step="0.05" value={scale} onChange={e=>setScale(Number(e.target.value))}/></label><label>MOVE LEFT / RIGHT <input type="range" min="-35" max="35" value={x} onChange={e=>setX(Number(e.target.value))}/></label><label>MOVE UP / DOWN <input type="range" min="-35" max="35" value={y} onChange={e=>setY(Number(e.target.value))}/></label><div className="crop-controls"><button type="button" onClick={onCancel}>Cancel</button><button type="button" className="gold-button" onClick={()=>onSave({scale,x,y})}>Use this crop <Check size={15}/></button></div></section></div> }
function CountryPicker({value,onChange}) { const [open,setOpen]=useState(false); const [search,setSearch]=useState(''); const chosen=countries.find(c=>c.country===value); const filtered=countries.filter(c=>c.country.toLowerCase().includes(search.toLowerCase())); return <div className="country-picker"><button type="button" className="country-trigger" onClick={()=>setOpen(!open)}><span>{chosen?.flag}</span>{value}<ChevronDown size={16}/></button>{open&&<div className="country-list"><div className="country-search"><Search size={15}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your country..."/></div>{filtered.map(c=><button type="button" key={c.country} onClick={()=>{onChange(c.country);setOpen(false);setSearch('')}}><span>{c.flag}</span><b>{c.country}</b>{c.country===value&&<Check size={15}/>}</button>)}</div>}</div> }
function PhoneField({value,onChange}) { const [phoneCountry,setPhoneCountry]=useState('Somalia'); const dialCode=countryDialCodes[phoneCountry]||'+252'; const localNumber=value.startsWith(dialCode)?value.slice(dialCode.length):value.replace(/^\+\d+\s*/,''); function pickCountry(nextCountry){setPhoneCountry(nextCountry);onChange(`${countryDialCodes[nextCountry]||'+252'}${localNumber}`)} return <div className="phone-field"><CountryPicker value={phoneCountry} onChange={pickCountry}/><label className="phone-entry"><span>{dialCode}</span><input type="tel" inputMode="tel" value={localNumber} onChange={e=>onChange(`${dialCode}${e.target.value.replace(/[^0-9\s-]/g,'')}`)} placeholder="61 234 5678" required/></label><small>Your selected country code is added automatically.</small></div> }
function Register({done}) { const [names,setNames]=useState(''); const [username,setUsername]=useState(''); const [email,setEmail]=useState(''); const [phone,setPhone]=useState(''); const [home,setHome]=useState('Somalia'); const [eventDate,setEventDate]=useState(''); const [venue,setVenue]=useState(''); const [hero,setHero]=useState({images:[defaultHero]}); function submit(e){e.preventDefault(); if(!names||!username||!email||!phone||!eventDate)return;done({names,username:username.toLowerCase().trim().replace(/\s+/g,'-'),email,phone,home,eventDate,venue,hero});} return <section className="register-page"><div className="register-copy"><span className="portal-chip">FOR COUPLES</span><h1>Your wedding deserves a beautiful first impression.</h1><p>Choose the photo every guest sees, frame it perfectly, then add the real details of your celebration.</p><ul><li><Check size={16}/> Crop the default image or replace it with your own</li><li><Check size={16}/> Set your real wedding date and venue</li><li><Check size={16}/> Preview the same hero your guests will see</li></ul></div><form className="register-card" onSubmit={submit}><h2>Create your wedding wall</h2><label>COUPLE NAMES<input value={names} onChange={e=>setNames(e.target.value)} placeholder="e.g. Ayaan & Hamza" required/></label><label>CHOOSE YOUR WALL ADDRESS<input value={username} onChange={e=>setUsername(e.target.value.replace(/[^a-zA-Z0-9-\s]/g,''))} placeholder="ayaan-hamza" required/><small>congrats.com/{username.toLowerCase().trim().replace(/\s+/g,'-')||'your-wall'}</small></label><div className="event-fields"><label>WEDDING DATE<input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)} required/></label><label>VENUE / CITY<input value={venue} onChange={e=>setVenue(e.target.value)} placeholder="e.g. Mogadishu, Somalia"/></label></div><label>EMAIL ADDRESS<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><div><label>MOBILE NUMBER</label><PhoneField value={phone} onChange={setPhone}/></div><div><label>YOUR COUNTRY</label><CountryPicker value={home} onChange={setHome}/></div><div><label>YOUR HERO PHOTO</label><MediaCropField value={hero} onChange={setHero} hero defaultImage={defaultHero}/></div><button className="gold-button">Create account & wall <Heart size={15} fill="currentColor"/></button></form></section> }
function Wish({w,reactToWish,openWish}) { const flag=w.flag||countries.find(c=>c.country===w.country)?.flag||'🌍'; const images=(w.images||w.photos||[]).map(image=>typeof image==='string'?image:image.url); return <article className="wish"><header><div className="initials">{w.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h3>{w.name} <span>{w.emoji}</span></h3><p>{flag} {w.country}</p></div></header><blockquote>“{w.message}”</blockquote>{images.length>0&&<button className="wish-media" onClick={()=>openWish(w)}><img src={images[0]} alt="Celebration attachment"/>{images.length>1&&<b>View all {images.length} photos</b>}</button>}{w.video&&<div className="video">▶ <span>Video greeting attached</span></div>}<div className="wish-actions"><button onClick={()=>reactToWish(w.id,'like')}><ThumbsUp size={14}/> {w.reactions?.like||0}</button><button onClick={()=>reactToWish(w.id,'love')}><Heart size={14}/> {w.reactions?.love||0}</button><button onClick={()=>openWish(w)}><MessageCircle size={14}/> {w.comments?.length||0}</button></div><time>{w.date}</time></article> }
function Dashboard({couple,wishes,openWall}) { return <section className="admin"><div className="admin-head"><div><span>YOUR WEDDING WALL IS LIVE</span><h1>Welcome, {couple.name}</h1></div><button className="dashboard-open" onClick={openWall}>Open your wall</button></div><div className="dashboard-link"><span>Your shareable link</span><b>congrats.com/{couple.username}</b><p>Send this link to your friends and family so they can find your wall and leave a blessing.</p></div><div className="metrics"><Metric label="Blessings received" value={wishes.length}/><Metric label="Countries reached" value={new Set(wishes.map(w=>w.country)).size}/><Metric label="Wall visitors" value="0"/><Metric label="Wall status" value="Live"/></div><div className="moderation"><div><h2>Recent blessings</h2>{wishes.slice(0,4).map(w=><article key={w.id}><div><b>{w.emoji} {w.name}</b><span>{w.country} · {w.date}</span><p>“{w.message}”</p></div></article>)}</div><aside><h2>Wall details</h2><div className="sync"><b>● Your wall is searchable</b><p>Guests can search for <strong>@{couple.username}</strong> from the home page, then post their congratulations.</p></div></aside></div></section> }
function WishModal({wish,close,reactToWish,commentOnWish}) { const [comment,setComment]=useState(''); const [zoom,setZoom]=useState(1); const images=(wish.images||wish.photos||[]).map(image=>typeof image==='string'?image:image.url); return <div className="overlay"><section className="wish-modal"><button className="close" onClick={close}><X/></button><div className="modal-media"><div className="zoom-controls"><button onClick={()=>setZoom(Math.max(1,zoom-.25))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(2.5,zoom+.25))}>+</button></div>{images.length?images.map((image,index)=><img key={image} src={image} style={{transform:`scale(${zoom})`}} alt={`Shared celebration ${index+1}`}/>):<div className="video">▶ <span>Video greeting attached</span></div>}</div><div className="modal-content"><h2>{wish.emoji} {wish.name}</h2><p>“{wish.message}”</p><div className="wish-actions"><button onClick={()=>reactToWish(wish.id,'like')}><ThumbsUp size={14}/> Like {wish.reactions?.like||0}</button><button onClick={()=>reactToWish(wish.id,'love')}><Heart size={14}/> Love {wish.reactions?.love||0}</button></div><h3>Comments ({wish.comments?.length||0})</h3><div className="comments">{wish.comments?.length?wish.comments.map(comment=><article key={comment.id}><p>{comment.text}</p><time>{comment.date}</time></article>):<p className="empty">Be the first to leave a comment.</p>}</div><form className="comment-form" onSubmit={e=>{e.preventDefault();commentOnWish(wish.id,comment);setComment('')}}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Write a comment..."/><button>Post</button></form></div></section></div> }
function AdminLogin({success}) { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); async function submit(e){e.preventDefault(); try { const {error:signInError}=await supabase.auth.signInWithPassword({email:email.trim(),password}); if(signInError) throw signInError; const {data:isAdmin,error:roleError}=await supabase.rpc('is_admin'); if(roleError) throw roleError; if(!isAdmin) { await supabase.auth.signOut(); throw new Error('This account does not have admin access.'); } success(); } catch(error) { setError(error.message); }} return <section className="admin-login"><form onSubmit={submit}><span>SECURE ADMIN ACCESS</span><h1>Admin sign in</h1><p>Use the Supabase Auth email and password assigned to the platform administrator.</p><label>ADMIN EMAIL<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="admin@example.com" required/></label><label>PASSWORD<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="login-error">{error}</p>}<button className="gold-button">Sign in securely <KeyRound size={15}/></button></form></section> }

function UserAccess({back}) { const [method,setMethod]=useState('email'); const [identity,setIdentity]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [message,setMessage]=useState(''); async function send(e){e.preventDefault(); try { if(method==='email') { const {error}=await supabase.auth.signInWithOtp({email:identity.trim(),options:{emailRedirectTo:window.location.origin}}); if(error) throw error; setSent(true); setMessage('We sent a secure sign-in link to your email. Open it to return directly to your dashboard.'); } else { const {error}=await supabase.auth.signInWithOtp({phone:identity.trim()}); if(error) throw error; setSent(true); setMessage('We sent a verification code to your phone.'); } } catch(error) { setMessage(error.message); } } async function verify(e){e.preventDefault(); try { const {error}=await supabase.auth.verifyOtp({phone:identity.trim(),token:code.trim(),type:'sms'}); if(error) throw error; setMessage('Verified. Opening your dashboard...'); } catch(error) { setMessage(error.message); } } return <section className="admin-login"><form onSubmit={sent&&method==='phone'?verify:send}><button type="button" className="back-access" onClick={back}>← Back</button><span>YOUR WEDDING DASHBOARD</span><h1>Welcome back</h1><p>Use the same email or mobile number used when your wall was registered.</p><div className="access-methods"><button type="button" className={method==='email'?'selected':''} onClick={()=>{setMethod('email');setSent(false);setMessage('')}}>Email</button><button type="button" className={method==='phone'?'selected':''} onClick={()=>{setMethod('phone');setSent(false);setMessage('')}}>Mobile</button></div><label>{method==='email'?'EMAIL ADDRESS':'MOBILE NUMBER'}<input type={method==='email'?'email':'tel'} value={identity} onChange={e=>setIdentity(e.target.value)} placeholder={method==='email'?'you@example.com':'+252 ...'} required/></label>{sent&&method==='phone'&&<label>VERIFICATION CODE<input inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)} placeholder="123456" required/></label>}{message&&<p className={message.includes('sent')||message.includes('Verified')?'access-message':'login-error'}>{message}</p>}<button className="gold-button">{sent&&method==='phone'?'Verify and open dashboard':method==='email'?'Send secure email link':'Send verification code'} <Check size={15}/></button></form></section> }
function Admin({couples,wishes,setWishes,setCouples,logout}) { const [analytics,setAnalytics]=useState(null); useEffect(()=>{ let active=true; const refresh=async()=>{ const {data,error}=await supabase.rpc('get_site_visit_metrics'); if(!error&&active&&data?.[0]) setAnalytics(data[0]); }; refresh(); const timer=window.setInterval(refresh,30000); return()=>{active=false;window.clearInterval(timer)}; },[]); return <section className="admin"><div className="admin-head"><div><span>CONGRATS ENTERPRISE MANAGEMENT</span><h1>Live Admin Control</h1></div><button onClick={logout}>Logout Admin</button></div><div className="metrics"><Metric label="Total Couples Registered" value={couples.length}/><Metric label="Blessings Published" value={wishes.length}/><Metric label="Website visits" value={analytics?.website_visits??'—'}/><Metric label="Unique visitors" value={analytics?.unique_visitors??'—'}/></div><div className="moderation"><div><h2>Blessings moderation</h2>{wishes.length?wishes.map(w=><article key={w.id}><div><b>{w.emoji} {w.name}</b><span>{w.country} · Wall: @{couples.find(c=>c.id===w.coupleId)?.username||'unknown'}</span><p>“{w.message}”</p></div><button onClick={()=>setWishes(wishes.filter(x=>x.id!==w.id))}>Remove post</button></article>):<p className="empty">No blessings to review yet.</p>}</div><aside><h2>Registered walls</h2>{couples.length?couples.map(c=><div className="registry" key={c.id}><img src={c.image} alt=""/><span><b>{c.name}</b><small>@{c.username}</small></span><button className="remove-wall" onClick={()=>{setCouples(couples.filter(x=>x.id!==c.id));setWishes(wishes.filter(w=>w.coupleId!==c.id))}}>Remove</button></div>):<p className="empty">No registered walls.</p>}<div className="sync"><b>● Administration mode</b><p>You can remove harmful content and fraudulent walls here. Supabase authentication and audit logs should replace this local-only control before public launch.</p></div></aside></div></section>}
function Metric({label,value}) { return <div><span>{label}</span><b>{value}</b></div>}
function Footer({openGuide,goHome}) {return <footer><div><h3>CONGRATS</h3><p>A simple place for couples to collect memories, wishes, and love from the people who matter.</p></div><div><h4>HOW IT WORKS</h4><p>• Create your wall</p><p>• Share your address</p><p>• Receive blessings</p></div><div><h4>HELPFUL LINKS</h4><button onClick={openGuide}>Help Guide & Instructions</button><button onClick={goHome}>Search for a Wall</button></div><div><h4>COPYRIGHT</h4><p>© 2026 Congrats Platform. All rights reserved.</p></div></footer>}
function Guide({close}) {return <div className="overlay"><section className="guide"><button className="close" onClick={close}><X/></button><span>CONGRATS HELP CENTER</span><h2>User Guide & Registry Info</h2><article><b>1. Setup Your Wedding Wall</b><p>Register your celebration, choose a unique username, and share your personal wall link with every guest.</p></article><article><b>2. The Live Blessings Feed</b><p>Guests can write a message, choose an emoji, and attach photos or videos that appear instantly on your wall.</p></article><article><b>3. Moderate Your Celebration</b><p>The dashboard gives couples a simple space to keep their wall feeling personal and joyful.</p></article><button className="gold-button" onClick={close}>Close Help Center</button></section></div>}
createRoot(document.getElementById('root')).render(<App/>);
